#!/usr/bin/env python3
"""Serve a flat-RoPE OLMo 3 checkpoint under Transformers 5.17 and vLLM 0.24.

The AISI checkpoints were saved by Transformers 5.3.0.dev0 with one flat
``rope_parameters`` dict (YaRN). Transformers 5.17 expects OLMo 3's
``rope_parameters`` to be keyed by layer type and fails config validation on
the flat form (``'float' object has no attribute 'get'``).

The nested form written here reproduces how AISI's own serving generated
every rollout and eval sample. Their vLLM (0.18.1rc1.dev193+g497e234d3, in
their uv.lock) builds OLMo 3 attention with "Rope scaling is only applied on
full attention layers": full-attention layers take the flat dict, and
sliding-window layers take ``{"rope_type": "default", "rope_theta": theta}``.
(Their HF training forward at transformers 11b1906d instead applied the one
YaRN embedding to every layer; this file follows the serving path, because the
eval numbers we replicate were generated by vLLM.)

vLLM 0.24's native OLMo2 runner in turn wants a flat dict for the full-attention
profile only, so the overlay also emits that dict for ``--hf-overrides`` --
the same adaptation as ``project.backends._flatten_olmo3_rope_parameters``.

    python scripts/olmo3_rope_config.py SRC_MODEL_DIR OVERLAY_DIR > full_rope.json

The overlay symlinks every file in SRC except config.json, so stored
checkpoints are never modified.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

LAYER_TYPES = ("full_attention", "sliding_attention")


def is_flat(rope: object) -> bool:
    return isinstance(rope, dict) and not any(key in rope for key in LAYER_TYPES)


def nest_rope_parameters(config: dict) -> dict:
    """Return a copy of an OLMo 3 config with rope_parameters keyed by layer type."""
    rope = config.get("rope_parameters")
    if not is_flat(rope):
        return dict(config)
    layer_types = set(config.get("layer_types") or [])
    if not layer_types or not layer_types <= set(LAYER_TYPES):
        raise ValueError(f"unexpected OLMo 3 layer_types: {sorted(layer_types)}")
    if "rope_theta" not in rope:
        raise ValueError("flat rope_parameters has no rope_theta")
    nested = {
        "full_attention": dict(rope),
        "sliding_attention": {"rope_type": "default", "rope_theta": rope["rope_theta"]},
    }
    return {**config, "rope_parameters": nested}


def full_attention_profile(config: dict) -> dict:
    """The flat dict vLLM 0.24's native OLMo2 runner consumes for full attention."""
    rope = nest_rope_parameters(config)["rope_parameters"]
    if rope["full_attention"].get("rope_theta") != rope["sliding_attention"].get("rope_theta"):
        raise ValueError("vLLM 0.24 cannot run OLMo 3 with different full/sliding rope_theta")
    return dict(rope["full_attention"])


def build_overlay(src: Path, dst: Path) -> dict:
    config = json.loads((src / "config.json").read_text())
    if config.get("model_type") != "olmo3":
        raise ValueError(f"{src} is not an OLMo 3 checkpoint")
    dst.mkdir(parents=True, exist_ok=False)
    for path in sorted(src.iterdir()):
        if path.name != "config.json":
            (dst / path.name).symlink_to(path.resolve())
    (dst / "config.json").write_text(json.dumps(nest_rope_parameters(config), indent=2) + "\n")
    return full_attention_profile(config)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("src", type=Path)
    ap.add_argument("dst", type=Path)
    args = ap.parse_args()
    print(json.dumps(build_overlay(args.src, args.dst)))


if __name__ == "__main__":
    main()
